In [1]:
!pip install gymnasium


Defaulting to user installation because normal site-packages is not writeable


In [6]:
import gymnasium as gym
import numpy as np
import time
import datetime

import import_ipynb
from dqn_p5 import DQN
from dqn_p5 import DQN_search

In [9]:


game_name = "CartPole-v0"
env = gym.make(game_name)
in_states = env.observation_space.shape[0]
out_actions = env.action_space.n

env.close()

N_TESTS = 5
s_res_cnt = 0
this_time_start = time.time()

ct = datetime.datetime.now()
ct = str(ct)
ct = ct.replace(":", "-")
ct = ct.replace(" ", "_")
ct = ct[:-7]
ct = '00/'+ct
# '0_5_3_a/'

for i in range(N_TESTS):
    print(i)
    search = DQN_search(dqn_model = DQN(ct = ct+'/'+str(i), game_name = game_name, mini_batch_size = 64, num_divisions = 50))
    atypes = ['', 'ReLU', 'ReLU', 'Linear']
    search.set_a_type_array(atypes)
    search.set_lr(0.1)
    start_net_shape = np.array([in_states, 3, 3, out_actions])
    shape_steps = np.array([[0, 1, 0, 0], [0, 0, 1, 0]])
    final_shape = np.array([in_states, 10, 10, out_actions])
    n_models = 3
    TSR = 95
    test_res, shape, good_policy = search.search(n_models, TSR, epochs = 10000, 
                                                 start_shape = np.array(start_net_shape), 
                                                 shape_steps = shape_steps,
                                                 final_shape = final_shape,
                                                 adaptive_n_models = True,
                                                 min_best_result = -10
                                                )
    if (test_res!= False):
        s_res_cnt+=1

this_time_end = time.time()
diff_time = (this_time_end - this_time_start)/60
print(diff_time)

0
0 [4 3 3 2]
Best rewards so far: 14.0
Best rewards so far: 24.0
Best rewards so far: 25.0
Best rewards so far: 30.0
Best rewards so far: 32.0
Best rewards so far: 38.0
Best rewards so far: 51.0
Best rewards so far: 61.0
Best rewards so far: 69.0
Best rewards so far: 77.0
Best rewards so far: 101.0
Episode 1000 Epsilon 0.900300000000011
Episode 2000 Epsilon 0.800300000000022
Episode 3000 Epsilon 0.700300000000033
Best rewards so far: 107.0
Episode 4000 Epsilon 0.600300000000044
Episode 5000 Epsilon 0.500300000000055
Best rewards so far: 278.0
Episode 6000 Epsilon 0.40030000000006605
Best rewards so far: 300.0
Episode 7000 Epsilon 0.30030000000007706
Episode 8000 Epsilon 0.20030000000008807
Episode 9000 Epsilon 0.10030000000009566
Episode 10000 Epsilon 0.01
test_res  20.0
medium_reward  48.73
0 [4 3 3 2]
Best rewards so far: 47.0
Best rewards so far: 58.0
Best rewards so far: 62.0
Best rewards so far: 64.0
Best rewards so far: 69.0
Best rewards so far: 71.0
Best rewards so far: 76.0
Ep

In [12]:
print(100.0*s_res_cnt/N_TESTS)

100.0


In [4]:

if (test_res!= False):
    model_ = DQN(game_name = game_name, mini_batch_size = 64, num_divisions = 50)
    res = model_.test(good_policy, 10, render = True)
    print(res)

(100.0, 200.0, [200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0, 200.0])


In [ ]:
model_ = DQN(ct = ct+'/'+str(i), game_name = game_name, mini_batch_size = 64, num_divisions = 50)

res = model_.test(good_policy, 10, render = True)


In [13]:


game_name = "CartPole-v0"
env = gym.make(game_name)
in_states = env.observation_space.shape[0]
out_actions = env.action_space.n

env.close()

N_TESTS = 10
s_res_cnt = 0
this_time_start = time.time()

ct = datetime.datetime.now()
ct = str(ct)
ct = ct.replace(":", "-")
ct = ct.replace(" ", "_")
ct = ct[:-7]
ct = '0_10/'+ct


found_shapes = []

for i in range(N_TESTS):
    print(i)
    search = DQN_search(dqn_model = DQN(ct = ct+'/'+str(i), game_name = game_name, mini_batch_size = 64, num_divisions = 50))
    atypes = ['', 'ReLU', 'ReLU', 'Linear']
    search.set_a_type_array(atypes)
    search.set_lr(0.1)
    start_net_shape = np.array([in_states, 3, 3, out_actions])
    shape_steps = np.array([[0, 1, 0, 0], [0, 0, 1, 0]])
    final_shape = np.array([in_states, 10, 10, out_actions])
    n_models = 1
    TSR = 95
    test_res, shape, good_policy = search.search(n_models, TSR, epochs = 10000, 
                                                 start_shape = np.array(start_net_shape), 
                                                 shape_steps = shape_steps,
                                                 final_shape = final_shape,
                                                 adaptive_n_models = True,
                                                 min_best_result = -10
                                                )
    if (test_res!= False):
        s_res_cnt+=1
        found_shapes.append((shape, good_policy))



0
0 [4 3 3 2]
Best rewards so far: 46.0
Best rewards so far: 66.0
Best rewards so far: 67.0
Best rewards so far: 72.0
Best rewards so far: 78.0
Best rewards so far: 83.0
Episode 1000 Epsilon 0.900200000000011
Best rewards so far: 92.0
Best rewards so far: 104.0
Episode 2000 Epsilon 0.800200000000022
Best rewards so far: 120.0
Episode 3000 Epsilon 0.700200000000033
Episode 4000 Epsilon 0.600200000000044
Episode 5000 Epsilon 0.500200000000055
Episode 6000 Epsilon 0.40020000000006606
Episode 7000 Epsilon 0.30020000000007707
Episode 8000 Epsilon 0.20020000000008809
Episode 9000 Epsilon 0.10020000000009566
Episode 10000 Epsilon 0.01
test_res  0.0
medium_reward  9.28
0 [4 3 3 2]
Best rewards so far: 11.0
Best rewards so far: 13.0
Best rewards so far: 26.0
Best rewards so far: 62.0
Best rewards so far: 80.0
Best rewards so far: 85.0
Episode 1000 Epsilon 0.900300000000011
Episode 2000 Epsilon 0.800300000000022
Best rewards so far: 88.0
Best rewards so far: 90.0
Episode 3000 Epsilon 0.700300000

In [14]:
this_time_end = time.time()
diff_time = (this_time_end - this_time_start)/60
print(diff_time)

for s, gp in found_shapes:
    print (s)

60.540038124720255
[4 6 5 2]
[4 3 3 2]
[4 5 4 2]
[4 5 4 2]
[4 5 5 2]
[4 4 4 2]
[4 7 6 2]
[4 3 3 2]
[4 4 3 2]
[4 6 6 2]


In [15]:


game_name = "CartPole-v0"
env = gym.make(game_name)
in_states = env.observation_space.shape[0]
out_actions = env.action_space.n

env.close()

N_TESTS = 10
s_res_cnt = 0
this_time_start = time.time()

ct = datetime.datetime.now()
ct = str(ct)
ct = ct.replace(":", "-")
ct = ct.replace(" ", "_")
ct = ct[:-7]
ct = '0_10_na/'+ct


found_shapes2 = []

for i in range(N_TESTS):
    print(i)
    search = DQN_search(dqn_model = DQN(ct = ct+'/'+str(i), game_name = game_name, mini_batch_size = 64, num_divisions = 50))
    atypes = ['', 'ReLU', 'ReLU', 'Linear']
    search.set_a_type_array(atypes)
    search.set_lr(0.1)
    start_net_shape = np.array([in_states, 3, 3, out_actions])
    shape_steps = np.array([[0, 1, 0, 0], [0, 0, 1, 0]])
    final_shape = np.array([in_states, 10, 10, out_actions])
    n_models = 1
    TSR = 95
    test_res, shape, good_policy = search.search(n_models, TSR, epochs = 10000, 
                                                 start_shape = np.array(start_net_shape), 
                                                 shape_steps = shape_steps,
                                                 final_shape = final_shape,
                                                 adaptive_n_models = False
                                                )
    if (test_res!= False):
        s_res_cnt+=1
        found_shapes2.append((shape, good_policy))

this_time_end = time.time()
diff_time = (this_time_end - this_time_start)/60
print(diff_time)

for s, gp in found_shapes:
    print (s)

0
0 [4 3 3 2]
Best rewards so far: 34.0
Best rewards so far: 46.0
Best rewards so far: 49.0
Best rewards so far: 51.0
Best rewards so far: 58.0
Best rewards so far: 86.0
Best rewards so far: 105.0
Episode 1000 Epsilon 0.900100000000011
Episode 2000 Epsilon 0.800100000000022
Episode 3000 Epsilon 0.700100000000033
Episode 4000 Epsilon 0.600100000000044
Episode 5000 Epsilon 0.5001000000000551
Episode 6000 Epsilon 0.40010000000006607
Episode 7000 Epsilon 0.3001000000000771
Episode 8000 Epsilon 0.2001000000000881
Episode 9000 Epsilon 0.10010000000009565
Episode 10000 Epsilon 0.01
test_res  0.0
medium_reward  12.32
0 [4 4 3 2]
Best rewards so far: 17.0
Best rewards so far: 63.0
Best rewards so far: 64.0
Best rewards so far: 67.0
Best rewards so far: 69.0
Best rewards so far: 83.0
Best rewards so far: 91.0
Best rewards so far: 102.0
Episode 1000 Epsilon 0.900100000000011
Episode 2000 Epsilon 0.800100000000022
Best rewards so far: 110.0
Best rewards so far: 154.0
Best rewards so far: 161.0
Epi

In [16]:
for s, gp in found_shapes2:
    print (s)

[4 4 3 2]
[4 5 5 2]
[4 5 4 2]
[4 4 3 2]
[4 6 6 2]
[4 5 4 2]
[4 5 5 2]
[4 5 4 2]


In [17]:


game_name = "CartPole-v0"
env = gym.make(game_name)
in_states = env.observation_space.shape[0]
out_actions = env.action_space.n

env.close()

N_TESTS = 5
s_res_cnt = 0
this_time_start = time.time()

ct = datetime.datetime.now()
ct = str(ct)
ct = ct.replace(":", "-")
ct = ct.replace(" ", "_")
ct = ct[:-7]
ct = '0_5_3_na/'+ct


found_shapes3 = []

for i in range(N_TESTS):
    print(i)
    search = DQN_search(dqn_model = DQN(ct = ct+'/'+str(i), game_name = game_name, mini_batch_size = 64, num_divisions = 50))
    atypes = ['', 'ReLU', 'ReLU', 'Linear']
    search.set_a_type_array(atypes)
    search.set_lr(0.1)
    start_net_shape = np.array([in_states, 3, 3, out_actions])
    shape_steps = np.array([[0, 1, 0, 0], [0, 0, 1, 0]])
    final_shape = np.array([in_states, 10, 10, out_actions])
    n_models = 3
    TSR = 95
    test_res, shape, good_policy = search.search(n_models, TSR, epochs = 10000, 
                                                 start_shape = np.array(start_net_shape), 
                                                 shape_steps = shape_steps,
                                                 final_shape = final_shape,
                                                 adaptive_n_models = False
                                                )
    if (test_res!= False):
        s_res_cnt+=1
        found_shapes3.append((shape, good_policy))

this_time_end = time.time()
diff_time = (this_time_end - this_time_start)/60
print(diff_time)

for s, gp in found_shapes3:
    print (s)

0
0 [4 3 3 2]
Best rewards so far: 37.0
Best rewards so far: 57.0
Best rewards so far: 62.0
Best rewards so far: 79.0
Best rewards so far: 86.0
Best rewards so far: 140.0
Episode 1000 Epsilon 0.900200000000011
Episode 2000 Epsilon 0.800200000000022
Episode 3000 Epsilon 0.700200000000033
Episode 4000 Epsilon 0.600200000000044
Episode 5000 Epsilon 0.500200000000055
Episode 6000 Epsilon 0.40020000000006606
Episode 7000 Epsilon 0.30020000000007707
Episode 8000 Epsilon 0.20020000000008809
Episode 9000 Epsilon 0.10020000000009566
Episode 10000 Epsilon 0.01
test_res  0.0
medium_reward  9.21
1 [4 3 3 2]
Best rewards so far: 22.0
Best rewards so far: 26.0
Best rewards so far: 32.0
Best rewards so far: 34.0
Best rewards so far: 41.0
Best rewards so far: 51.0
Best rewards so far: 59.0
Best rewards so far: 60.0
Best rewards so far: 65.0
Best rewards so far: 112.0
Episode 1000 Epsilon 0.900300000000011
Episode 2000 Epsilon 0.800300000000022
Episode 3000 Epsilon 0.700300000000033
Episode 4000 Epsilo